* Description

This code is based on cl-cpp-generator2/example/08_copernicus_radar.
The code was started in December 2020.

I learned a bit more about how to split C++ code into modules and
tried to apply this here.  Each cpp file also has a hpp file with
classes and function definitions.

I added a CMake based build system and attempted to embed Python.

* Overview of my code bases related to synthetic aperture radar

| start date | comment                                         | link                                                                               | 
|------------+-------------------------------------------------+------------------------------------------------------------------------------------+
| Feb 2016   | OpenCL based focussing of ultrasound in k-space | not public ([1] and [2] are better)                                                |
| Aug 2018   | Lisp prototye of parser                         | https://github.com/plops/satellite-plot                                            |
| Nov 2019   | first c++ code                                  | https://github.com/plops/cl-cpp-generator2/tree/master/example/08_copernicus_radar |
| Sep 2020   | GTK UI attempt                                  | https://github.com/plops/cl-cpp-generator2/tree/master/example/33_copernicus_gtk   |
| Dec 2020   | separate C++ project, CMake, embedded python    | https://github.com/plops/copernicus-radar                                          |

* Compilation
#+begin_example
cd source
mkdir build
cmake -G Ninja ..
ninja
#+end_example

* How to run

Download a raw copernicus sentinel 1 dataset from https://scihub.copernicus.eu.

I used this link (not sure if it works):
https://scihub.copernicus.eu/dhus/odata/v1/Products(%278034f2a7-0e1c-4270-82dc-0c5bc3211cb7%27)/Nodes(%27S1A_S3_RAW__0SDH_20210221T213548_20210221T213613_036693_044FED_A100.SAFE%27)/Nodes(%27s1a-s3-raw-s-hh-20210221t213548-20210221t213613-036693-044fed.dat%27)/$value


#+begin_example
cd source/build
./mytest ~/Downloads/s1a-s3-raw-s-hh-20210221t213548-20210221t213613-036693-044fed.dat
#+end_example


* References

[1] https://hforsten.com/synthetic-aperture-radar-imaging.html
[2] https://hforsten.com/third-version-of-homemade-6-ghz-fmcw-radar.html
